AllCops:
  Include:
    - Rakefile
    - config.ru
    - Gemfile
    - bin/docker-build-server
    - docker-build-server.gemspec
  Exclude:
    - vendor/**/*.rb
    - tmp/*.rb

Documentation:
  Enabled: false

DoubleNegation:
  Enabled: false

LineLength:
  Max: 100

RegexpLiteral:
  Enabled: false
