AllCops:
  Includes:
    - Rakefile
    - config.ru
    - Gemfile
    - bin/docker-build-server
    - docker-build-server.gemspec
  Excludes:
    - vendor/**/*.rb
    - tmp/*.rb

Documentation:
  Enabled: false
