#!/bin/bash
set -e

export REDIS_URL="${REDIS_URL:-redis://localhost:6379}"
export REDIS_NAMESPACE="${REDIS_NAMESPACE:-docker-build-server:}"
export DOCKER_BUILD_QUEUE="${DOCKER_BUILD_QUEUE:-docker-build}"

cd "$(dirname $0)"
exec bundle exec puma \
  -e "${RACK_ENV:-development}" \
  -p "${PORT:-5000}" \
  -C ./config/puma.rb
